// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw7A16VAq-sVxEqkLVzm0vY2yQfi-dHxg',
    appId: '1:720120435177:web:128d4e65aff1d305eb7b78',
    messagingSenderId: '720120435177',
    projectId: 'kochanet-measure-app',
    authDomain: 'kochanet-measure-app.firebaseapp.com',
    databaseURL: 'https://kochanet-measure-app-default-rtdb.firebaseio.com',
    storageBucket: 'kochanet-measure-app.appspot.com',
    measurementId: 'G-T98HCZXP64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMqB0W_AQi9sZzQ3dYTH4ffTLz8r4dbDI',
    appId: '1:720120435177:android:d1fde9c840fdbc33eb7b78',
    messagingSenderId: '720120435177',
    projectId: 'kochanet-measure-app',
    databaseURL: 'https://kochanet-measure-app-default-rtdb.firebaseio.com',
    storageBucket: 'kochanet-measure-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsqpS9V6F1-Hu9EmVCfmDyse_luUjq84s',
    appId: '1:720120435177:ios:f50fa7a1040798b8eb7b78',
    messagingSenderId: '720120435177',
    projectId: 'kochanet-measure-app',
    databaseURL: 'https://kochanet-measure-app-default-rtdb.firebaseio.com',
    storageBucket: 'kochanet-measure-app.appspot.com',
    iosBundleId: 'com.example.kochanetMeasureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsqpS9V6F1-Hu9EmVCfmDyse_luUjq84s',
    appId: '1:720120435177:ios:07e370f1207e2b91eb7b78',
    messagingSenderId: '720120435177',
    projectId: 'kochanet-measure-app',
    databaseURL: 'https://kochanet-measure-app-default-rtdb.firebaseio.com',
    storageBucket: 'kochanet-measure-app.appspot.com',
    iosBundleId: 'com.example.kochanetMeasureApp.RunnerTests',
  );
}
